%YAML:1.0
# data
rgb_dir: /home/seungwon/Data/snu34/rgb/
depth_dir: /home/seungwon/Data/snu34/depth/

# camera intrinsics
camera.fx: 435.47239
camera.fy: 435.47239
camera.cx: 424
camera.cy: 240

# feature
feature_type: ORB
num_features: 500
num_features_init: 500
num_features_tracking: 100
knn_ratio: 0.7

# tracking
match_threshold_tracking: 30
# keyframe
match_threshold_keyframe: 100
window_size: 5
