%YAML:1.0
# data
rgb_dir: /home/seungwon/3DII/Fusion_o3d/data_o3d/image/
match_save_dir: /home/seungwon/3DII/Fusion_o3d/data_o3d/match/

# camera intrinsics
camera.fx: 4786.9338649532028
camera.fy: 4786.9338649532028
camera.cx: 750.0
camera.cy: 1000.0

height: 2000
width: 1500

# feature
feature_type: SIFT
num_features: 5000
knn_ratio: 0.8

match_threshold: 10
max: 33
