%YAML:1.0
# data
rgb_dir: /home/seungwon/3DII/Fusion_o3d/data_o3d/image/
match_save_dir: /home/seungwon/3DII/Fusion_o3d/data_o3d/match/

# camera intrinsics
camera.fx: 4786.9338649532028
camera.fy: 4786.9338649532028
camera.cx: 746.0
camera.cy: 995.0

height: 1990
width: 1492

# feature
feature_type: SIFT
num_features: 2000
knn_ratio: 0.7

match_threshold: 20
max: 33
