%YAML:1.0
# data
rgb_dir: /home/seungwon/Data/office3_clean/rgb/
depth_dir: /home/seungwon/Data/office3_clean/depth/

# camera intrinsics
camera.fx: 481.2
camera.fy: -480.0
camera.cx: 319.5
camera.cy: 239.5

height: 480
width: 640

# feature
feature_type: ORB
num_features: 2000
num_features_init: 2000
num_features_tracking_threshold: 500
knn_ratio: 0.7

# tracking
#match_threshold_tracking: 30
# keyframe
#match_threshold_keyframe: 500
window_size: 5
keyframe_min_dist_threshold: 0.05

max: 1240
